M48
; DRILL file {KiCad 7.0.9} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-01T15:43:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.7Y-2.7
X5.27Y-3.458
X5.27Y-4.102
X5.531Y-1.771
X6.235Y-5.761
X7.14Y-2.7
X7.872Y-5.761
T2
X6.964Y-3.444
X6.964Y-5.397
X7.869Y-3.444
X7.871Y-5.397
T0
M30
