M48
; DRILL file {KiCad 7.0.9} date Thursday, January 11, 2024 at 05:45:54 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-11T17:45:54+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X134.175Y-131.572
X134.518Y-152.146
X150.177Y-101.6
X152.4Y-50.8
X173.533Y-74.371
T0
M30
